/**
 * The API responses the browser tests are driven against, generated by the real API.
 *
 * The frontend suite stubs the network, which raises the obvious question: stubbed with
 * what? Hand-written JSON would drift from the contract the moment a field moved, and
 * the browser tests would keep passing against a server that no longer exists.
 *
 * So the fixtures are produced by driving the actual Fastify app -- the same routes, the
 * same pricing path, the same formatting -- with the Thetanuts client stubbed at its
 * module boundary. This file then asserts the checked-in copies still match. A backend
 * change that alters a response shape fails HERE, with an instruction, rather than
 * silently leaving the browser suite testing a fiction.
 *
 *     npm run fixtures      # regenerate after a deliberate contract change
 */
import { describe, it, expect, beforeAll, afterAll, vi } from "vitest";

vi.mock("../thetanuts/client.js", async () => await import("./stub-client.js"));
vi.mock("../supabase.js", async () => await import("./stub-supabase.js"));
vi.mock("../insurance/loan.js", async () => await import("./stub-loan.js"));

// The Risk Profile / Suggestion / Decision routes reach Supabase and the agents
// service -- neither exists in this test process, so they're mocked at the same
// module boundary suggestion.test.ts mocks them at. See the comment above
// `generated["risk-profile-unset"]` below for which of these fixtures that makes a
// mocked-passthrough capture versus genuine server code.
vi.mock("../supabase/riskProfiles.js", () => ({
  getRiskProfile: vi.fn(),
  setRiskProfile: vi.fn(),
}));
vi.mock("../strategy/suggest.js", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../strategy/suggest.js")>();
  return { ...actual, fetchSuggestion: vi.fn() };
});
vi.mock("../supabase/decisions.js", async (importOriginal) => {
  const actual = await importOriginal<typeof import("../supabase/decisions.js")>();
  return { ...actual, recordDecision: vi.fn() };
});
vi.mock("../supabase/fills.js", () => ({
  recordFill: vi.fn(),
  listFills: vi.fn(),
}));

import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";
import type { FastifyInstance } from "fastify";
import { buildApp } from "../app.js";
import { resetStub, state, chain, TRADER_ADDRESS, proveWallet } from "./stub-client.js";
import { registerUser } from "./stub-supabase.js";
import { resetStub as resetLoanStub, state as loanState } from "./stub-loan.js";
import { NOW, DEFAULT_BOOK, makeOrder, SPOT, PRICES } from "./fixtures.js";
import { getRiskProfile, setRiskProfile } from "../supabase/riskProfiles.js";
import { fetchSuggestion } from "../strategy/suggest.js";
import { recordDecision } from "../supabase/decisions.js";
import { listFills } from "../supabase/fills.js";

const mockedGetProfile = vi.mocked(getRiskProfile);
const mockedSetProfile = vi.mocked(setRiskProfile);
const mockedFetchSuggestion = vi.mocked(fetchSuggestion);
const mockedRecordDecision = vi.mocked(recordDecision);
const mockedListFills = vi.mocked(listFills);

vi.useFakeTimers({ toFake: ["Date"] });
vi.setSystemTime(NOW);
afterAll(() => vi.useRealTimers());

const DIR = fileURLToPath(new URL("../../../web/tests/fixtures/", import.meta.url));
const WRITE = process.env.WRITE_FIXTURES === "1";

/** The session every fixture is generated under, so its cardRefs resolve against each other. */
const SESSION = "fixtures";

/** The one signed-in account every fixture needing one (ADR-0014) is generated under. */
const ACCOUNT_TOKEN = "fixture-account-token";

/**
 * Every fixture, named up front.
 *
 * Static because `it.each` is evaluated at collection time, before anything has been
 * generated -- and because naming them here makes deleting one that the browser suite
 * depends on a failure rather than a route it mysteriously cannot stub.
 */
const NAMES = [
  "deck-down-1",
  "deck-down-2",
  "deck-down-3",
  "deck-up-1",
  "deck-empty",
  "depth-eth",
  "markets",
  "deck-sol-down-1",
  "deck-sol-down-2",
  "deck-sol-up-1",
  "deck-compressed",
  "session",
  "positions-empty",
  "positions-after-practice",
  "propose-agent",
  "propose-by-card",
  "propose-horizon-3",
  "practice",
  "auth-challenge",
  "fill-prepare",
  "fill-settle",
  "veto",
  "no-order",
  "refusal",
  "account",
  // --- Liquidation Cover surface -----------------------------------------------
  // Four QUOTE fixtures: the states the Cover surface has to render.
  "cover-healthy",
  "cover-tight",
  "cover-cbbtc",
  "cover-far-strike",
  // Five REFUSED fixtures: every refusal path the surface must handle gracefully.
  "cover-refused-multi-collateral",
  "cover-refused-no-debt",
  "cover-refused-already-liquidatable",
  "cover-refused-unsupported-collateral",
  "cover-refused-no-collateral",
  "risk-profile-unset",
  "risk-profile-balanced",
  "suggestion-unset",
  "suggestion-eth",
  "suggestion-eth-3d",
  "suggestion-no-signal",
  "decisions-accepted",
  "history",
] as const;

/**
 * Replace the capabilities with stable stand-ins.
 *
 * A `cardRef` is an HMAC under a per-session random key and a `proposalId` is a
 * randomUUID -- both unguessable by design, both different on every run. Comparing them
 * byte for byte would make this file fail every time it was run, so they are numbered in
 * order of first appearance instead.
 *
 * What survives is what the browser suite actually depends on: the figures, the strings,
 * the ordering, and the fact that a ref appearing in a Deck is the same ref the proposal
 * for that Card comes back under.
 */
function stabilise(value: unknown): unknown {
  const seen = new Map<string, string>();
  const swap = (s: string) => {
    if (/^[0-9a-f]{32}$/.test(s)) return seen.get(s) ?? (seen.set(s, `card-${seen.size}`), seen.get(s)!);
    if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(s)) return "proposal-id";
    return s;
  };
  const walk = (v: unknown): unknown => {
    if (typeof v === "string") return swap(v);
    if (Array.isArray(v)) return v.map(walk);
    if (v && typeof v === "object")
      return Object.fromEntries(Object.entries(v).map(([k, val]) => [swap(k), walk(val)]));
    return v;
  };
  return walk(value);
}

let app: FastifyInstance;
const generated: Record<string, unknown> = {};

const get = async (url: string, session = SESSION, accountToken?: string) =>
  (
    await app.inject({
      method: "GET",
      url,
      headers: { "x-session-id": session, ...(accountToken ? { "x-account-token": accountToken } : {}) },
    })
  ).json();

// `payload` is typed rather than left as `unknown`, which sends TypeScript down a
// different `inject` overload and loses the response type entirely.
const post = async (url: string, payload: Record<string, unknown>, session = SESSION, accountToken?: string) =>
  await app.inject({
    method: "POST",
    url,
    headers: { "x-session-id": session, ...(accountToken ? { "x-account-token": accountToken } : {}) },
    payload,
  });

const DOWN_1 = "/deck?asset=ETH&direction=DOWN&horizonDays=1&sizeUsdc=2";
const intent = { underlying: "ETH", direction: "DOWN", sizeUsdc: 2, horizonDays: 1 } as const;

// The Risk Profile / Suggestion / Decision routes now key on the signed-in account
// (ADR-0017), not a wallet -- so these three helpers below just need an account token,
// no wallet proof. OWNER is still used purely to compose the mocked response bodies
// below (riskProfiles.js/decisions.js are mocked at the module boundary in this file,
// so nothing here actually reads it off a session).
const OWNER = TRADER_ADDRESS.toLowerCase();

const getAsOwner = async (url: string) =>
  (await app.inject({ method: "GET", url, headers: { "x-session-id": SESSION, "x-account-token": ACCOUNT_TOKEN } })).json();

const putAsOwner = async (url: string, payload: Record<string, unknown>) =>
  (await app.inject({ method: "PUT", url, headers: { "x-session-id": SESSION, "x-account-token": ACCOUNT_TOKEN }, payload })).json();

const postAsOwner = async (url: string, payload: Record<string, unknown>) =>
  (await app.inject({ method: "POST", url, headers: { "x-session-id": SESSION, "x-account-token": ACCOUNT_TOKEN }, payload })).json();

beforeAll(async () => {
  resetStub();
  registerUser(ACCOUNT_TOKEN, { id: "cccccccc-0000-4000-8000-000000000003", email: "fixture@example.com" });
  app = await buildApp();

  // --- the ordinary surface -------------------------------------------------
  generated["deck-down-1"] = await get(DOWN_1);
  generated["deck-down-2"] = await get("/deck?asset=ETH&direction=DOWN&horizonDays=2&sizeUsdc=2");
  generated["deck-down-3"] = await get("/deck?asset=ETH&direction=DOWN&horizonDays=3&sizeUsdc=2");
  generated["deck-up-1"] = await get("/deck?asset=ETH&direction=UP&horizonDays=1&sizeUsdc=2");
  generated["depth-eth"] = await get("/depth?asset=ETH&horizonDays=1");
  /*
   * The rail is the one fixture that has to show all six markets, so it is generated
   * against a book that actually has six -- the default fixture book is ETH and BTC, and
   * a rail of four empty rows would demonstrate nothing about the thing being built.
   * The depths are lopsided on purpose: a one-sided market is what the split bar exists
   * to make visible without reading a number.
   */
  state.book = [
    ...DEFAULT_BOOK,
    makeOrder({ nonce: 50, id: 50, optionType: 0, strike: 104, perContract: 1.6, days: 1, symbol: "SOL", availableUsdc: 9000 }),
    makeOrder({ nonce: 50, id: 51, optionType: 1, strike: 100, perContract: 0.7, days: 1, symbol: "SOL", availableUsdc: 7000 }),
    makeOrder({ nonce: 51, id: 52, optionType: 0, strike: 700, perContract: 8, days: 1, symbol: "BNB", availableUsdc: 8000 }),
    makeOrder({ nonce: 51, id: 53, optionType: 1, strike: 670, perContract: 6, days: 1, symbol: "BNB", availableUsdc: 8000 }),
    // XRP quoting calls and nothing else -- the one-sided case, drawn as a full blue bar.
    makeOrder({ nonce: 52, id: 54, optionType: 0, strike: 1.4, perContract: 0.02, days: 1, symbol: "XRP", availableUsdc: 6000 }),
    makeOrder({ nonce: 53, id: 55, optionType: 1, strike: 7.1, perContract: 0.03, days: 1, symbol: "AVAX", availableUsdc: 5000 }),
    makeOrder({ nonce: 54, id: 56, optionType: 0, strike: 79000, perContract: 540, days: 1, symbol: "BTC", availableUsdc: 12000 }),
  ];
  generated["markets"] = await get("/markets");
  resetStub();
  generated["session"] = await get("/session");
  generated["positions-empty"] = await get("/positions");

  // The Trade Agent's own pick, and then every Card as an override -- so a browser test
  // can flick across the whole Deck and get the answer the server would really give.
  generated["propose-agent"] = (await post("/propose", intent)).json();

  const deck = generated["deck-down-1"] as { cards: Array<{ cardRef: string }> };
  const byCard: Record<string, unknown> = {};
  for (const card of deck.cards) {
    byCard[card.cardRef] = (await post("/propose", { ...intent, cardRef: card.cardRef })).json();
  }
  generated["propose-by-card"] = byCard;

  /*
   * The same intent asked at a horizon nothing on the book quotes.
   *
   * /propose takes the NEAREST live expiry and /deck filters on the exact one, so this
   * answer is the 2-day $2,380 put with `horizonDays: 2` -- not the 3 that was asked
   * for. Its cardRef is the only Card in `deck-down-2`, which is what makes the
   * mismatch testable in a browser: the surface has to end up rendering THAT row.
   */
  generated["propose-horizon-3"] = (await post("/propose", { ...intent, horizonDays: 3 })).json();

  // A Practice Run against a freshly minted proposal, plus the board it produces.
  const forPractice = (await post("/propose", intent)).json() as { proposalId: string };
  generated["practice"] = (await post("/practice", { proposalId: forPractice.proposalId })).json();
  generated["positions-after-practice"] = await get("/positions");

  // Proving wallet ownership -- the sign-in challenge (ADR-0012), which now also
  // requires a signed-in account (ADR-0014). The nonce is a fresh random value every
  // run (that is the point of it), so it is normalized to a fixed placeholder here
  // rather than through the shared `stabilise` below, which only replaces a whole
  // matching field value, not a value embedded inside a sentence.
  const challenge = (await post("/auth/challenge", { walletAddress: TRADER_ADDRESS }, SESSION, ACCOUNT_TOKEN)).json() as { message: string };
  generated["auth-challenge"] = {
    message: challenge.message.replace(/Nonce: [0-9a-f]{32}/, "Nonce: stable-nonce-for-fixtures"),
  };
  await proveWallet(app, SESSION, TRADER_ADDRESS, ACCOUNT_TOKEN);

  // A prepared fill, and settling it -- the non-custodial, chain-verified, account-gated
  // contract (ADR-0011, ADR-0012, ADR-0014).
  const forFill = (await post("/propose", intent)).json() as { proposalId: string };
  generated["fill-prepare"] = (
    await post("/fill/prepare", { proposalId: forFill.proposalId, walletAddress: TRADER_ADDRESS }, SESSION, ACCOUNT_TOKEN)
  ).json();
  state.receipt = { status: 1, to: chain.contracts.optionBook };
  generated["fill-settle"] = (
    await post("/fill/settle", { proposalId: forFill.proposalId, txHash: "0xFIXTURETX" }, SESSION, ACCOUNT_TOKEN)
  ).json();
  state.receipt = null;

  // The signed-in account's own view of itself -- settings plus the wallet just linked
  // by proveWallet() above.
  generated["account"] = await get("/account", SESSION, ACCOUNT_TOKEN);

  // --- the halt states ------------------------------------------------------
  process.env.COPILOT_REVIEW_FIXTURE = "veto";
  generated["veto"] = (await post("/propose", intent, "veto-session")).json();
  delete process.env.COPILOT_REVIEW_FIXTURE;

  state.book = [];
  generated["deck-empty"] = await get(DOWN_1, "empty-session");
  generated["no-order"] = (await post("/propose", intent, "empty-session")).json();

  /*
   * A cash-settled Underlying, so the browser suite exercises the path that did not
   * exist when it was written. SOL matters specifically: its calls settle in USDC, not
   * in the underlying, and it is identified by a price feed rather than by a token --
   * both of which the ETH fixtures would let a regression slip past.
   */
  state.book = [
    // ONE put at a day, THREE at two days. Not an arbitrary shape: one day is routinely
    // the emptiest cell in the whole book -- on a recent live snapshot ETH puts at one
    // day were a single Card against nine at four days. The surface must open on the
    // fullest expiry rather than the shortest, and a fixture where the shortest is also
    // the fullest could not tell the two rules apart.
    makeOrder({ nonce: 40, id: 40, optionType: 1, strike: 100, perContract: 0.71, days: 1, symbol: "SOL", iv: 0.74, availableUsdc: 10_000 }),
    makeOrder({ nonce: 41, id: 41, optionType: 1, strike: 98, perContract: 0.62, days: 2, symbol: "SOL", iv: 0.78, availableUsdc: 10_000 }),
    makeOrder({ nonce: 41, id: 42, optionType: 1, strike: 100, perContract: 1.04, days: 2, symbol: "SOL", iv: 0.74, availableUsdc: 10_000 }),
    makeOrder({ nonce: 41, id: 43, optionType: 1, strike: 102, perContract: 1.71, days: 2, symbol: "SOL", iv: 0.68, availableUsdc: 10_000 }),
    // Calls at one day only. So the two-day chip is live on Falls and DEAD on Rises --
    // the asymmetry the chips exist to show, and the reason a dead chip must not vanish.
    makeOrder({ nonce: 42, id: 44, optionType: 0, strike: 104, perContract: 1.59, days: 1, symbol: "SOL", iv: 0.69, availableUsdc: 10_000 }),
    makeOrder({ nonce: 42, id: 45, optionType: 0, strike: 106, perContract: 0.89, days: 1, symbol: "SOL", iv: 0.71, availableUsdc: 10_000 }),
  ];
  generated["deck-sol-down-1"] = await get("/deck?asset=SOL&direction=DOWN&horizonDays=1&sizeUsdc=2", "sol-session");
  generated["deck-sol-down-2"] = await get("/deck?asset=SOL&direction=DOWN&horizonDays=2&sizeUsdc=2", "sol-session");
  generated["deck-sol-up-1"] = await get("/deck?asset=SOL&direction=UP&horizonDays=1&sizeUsdc=2", "sol-session");
  resetStub();

  // --- a Deck whose chances have compressed, so the gradient stops carrying ---
  state.book = [
    makeOrder({ nonce: 30, optionType: 1, strike: 2440, perContract: 9.6, days: 1, iv: 0.45 }),
    makeOrder({ nonce: 30, optionType: 1, strike: 2445, perContract: 10.4, days: 1, iv: 0.45 }),
    makeOrder({ nonce: 30, optionType: 1, strike: 2450, perContract: 11.2, days: 1, iv: 0.45 }),
  ];
  generated["deck-compressed"] = await get(DOWN_1, "compressed-session");

  // --- the Trader's own ceiling refusing them -------------------------------
  resetStub();
  // Account-gated since audit B4 -- a session id alone can no longer move a ceiling, so
  // setting one up for this fixture now needs a signed-in caller like a real Trader.
  await post("/session/budget", { riskBudgetUsdc: 1 }, "broke-session", ACCOUNT_TOKEN);
  const refused = await post("/propose", intent, "broke-session");
  generated["refusal"] = { status: refused.statusCode, body: refused.json() };

  // --- Liquidation Cover surface --------------------------------------------
  //
  // GET /cover/quote drives `readLoan` (stubbed) then `assess()` (real), then the
  // route's own formatters. Every number in these fixtures is a real server output --
  // only the RPC read is replaced, matching the ticket's "highest point at which the
  // chain can be removed while keeping everything worth testing".
  //
  // `totalCollateralUsd` is set to `collateralAmount * aavePrice` exactly so the
  // MULTI_COLLATERAL identity check inside `assess()` always passes on QUOTE fixtures.
  // `aavePrice === thetanutsPrice` for the same reason: the PRICE_DIVERGENCE check is
  // the very first gate, and a 0% spread clears it without any rounding risk.

  // WETH, healthy loan -- health factor ~1.22. A calm position, nothing to warn about.
  loanState.next = {
    ok: true,
    loan: {
      collateral: "WETH",
      underlying: "ETH",
      collateralAmount: 1.5,
      totalCollateralUsd: 1.5 * SPOT,   // 3668.235 -- exact, passes the collateral identity
      totalDebtUsd: 2500,
      liquidationThreshold: 0.83,
      healthFactor: (1.5 * SPOT * 0.83) / 2500,  // ≈ 1.218
      aavePrice: SPOT,
      thetanutsPrice: SPOT,
    },
  };
  generated["cover-healthy"] = await get("/cover/quote?address=0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266");
  resetLoanStub();

  // WETH, tight loan -- health factor ~1.09. The strike lands just above spot (+1.2%),
  // so the "distance" figure reads as a small positive move rather than a fall.
  // This is also the case that motivates the signed distance: a positive distance means
  // "must rise to be struck", which a borrower needs to understand.
  loanState.next = {
    ok: true,
    loan: {
      collateral: "WETH",
      underlying: "ETH",
      collateralAmount: 1.5,
      totalCollateralUsd: 1.5 * SPOT,
      totalDebtUsd: 2800,
      liquidationThreshold: 0.83,
      healthFactor: (1.5 * SPOT * 0.83) / 2800,  // ≈ 1.087
      aavePrice: SPOT,
      thetanutsPrice: SPOT,
    },
  };
  generated["cover-tight"] = await get("/cover/quote?address=0x70997970C51812dc3A010C7d01b50e0d17dc79C8");
  resetLoanStub();

  // cbBTC collateral -- exercises the BTC price path and cbBTC's 8-decimal tokenAmount
  // formatter, which differs from WETH's 6-decimal one. Health factor ~1.52.
  loanState.next = {
    ok: true,
    loan: {
      collateral: "cbBTC",
      underlying: "BTC",
      collateralAmount: 0.05,
      totalCollateralUsd: 0.05 * PRICES.BTC,   // 3894.107
      totalDebtUsd: 2000,
      liquidationThreshold: 0.78,
      healthFactor: (0.05 * PRICES.BTC * 0.78) / 2000,  // ≈ 1.519
      aavePrice: PRICES.BTC,
      thetanutsPrice: PRICES.BTC,
    },
  };
  generated["cover-cbbtc"] = await get("/cover/quote?address=0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC");
  resetLoanStub();

  // WETH, large health factor (~5.07) -- strike lands 78% below spot, which trips the
  // far-strike warning in `assess()`. The warning threshold is `strikeDistanceFromSpot < -0.4`:
  //   liquidationPrice = 800 / (2.0 * 0.83) = 481.93
  //   targetStrike     = 481.93 * 1.1      = 530.12
  //   distance         = 530.12 / 2445.49 - 1 = -0.783 < -0.4  ✓
  loanState.next = {
    ok: true,
    loan: {
      collateral: "WETH",
      underlying: "ETH",
      collateralAmount: 2.0,
      totalCollateralUsd: 2.0 * SPOT,   // 4890.98
      totalDebtUsd: 800,
      liquidationThreshold: 0.83,
      healthFactor: (2.0 * SPOT * 0.83) / 800,  // ≈ 5.074
      aavePrice: SPOT,
      thetanutsPrice: SPOT,
    },
  };
  generated["cover-far-strike"] = await get("/cover/quote?address=0x90F79bf6EB2c4f870365E785982E1f101E93b906");
  resetLoanStub();

  // REFUSED: two assets held -- WETH and cbBTC together. On the real chain-reading
  // path this is detected inside `readLoan` itself, before `assess()` runs. The stub
  // mirrors that control flow by returning `ok: false` directly, with the same message
  // template `loan.ts` uses, filled in with concrete plausible numbers.
  loanState.next = {
    ok: false,
    refusal: {
      code: "MULTI_COLLATERAL",
      message:
        "This Loan holds both WETH and cbBTC. A Cover can only be priced for a " +
        "single-collateral Loan -- with a mix, Aave's blended threshold makes the liquidation price wrong " +
        "by tens of percent and nothing on screen would show it.",
    },
  };
  generated["cover-refused-multi-collateral"] = await get("/cover/quote?address=0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65");
  resetLoanStub();

  // REFUSED: no debt. The stub returns a valid WETH loan with `totalDebtUsd: 0`, which
  // real `assess()` catches at its second check and refuses with NO_DEBT. `healthFactor`
  // is Infinity, matching what `loan.ts` sets when Aave returns 2^256-1 for a debt-free
  // position -- `assess()` never reads it for this path, so it never reaches the formatter.
  loanState.next = {
    ok: true,
    loan: {
      collateral: "WETH",
      underlying: "ETH",
      collateralAmount: 1.0,
      totalCollateralUsd: SPOT,
      totalDebtUsd: 0,
      liquidationThreshold: 0.83,
      healthFactor: Infinity,
      aavePrice: SPOT,
      thetanutsPrice: SPOT,
    },
  };
  generated["cover-refused-no-debt"] = await get("/cover/quote?address=0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc");
  resetLoanStub();

  // REFUSED: health factor below 1 -- the loan can already be liquidated. The stub
  // returns debt > 0 and a plausible sub-1 health factor; real `assess()` catches it
  // at its fourth check (after PRICE_DIVERGENCE, NO_DEBT, MULTI_COLLATERAL all pass).
  loanState.next = {
    ok: true,
    loan: {
      collateral: "WETH",
      underlying: "ETH",
      collateralAmount: 1.0,
      totalCollateralUsd: SPOT,   // collateralAmount * aavePrice exactly -- MULTI_COLLATERAL passes
      totalDebtUsd: 3000,
      liquidationThreshold: 0.83,
      healthFactor: 0.947,
      aavePrice: SPOT,
      thetanutsPrice: SPOT,
    },
  };
  generated["cover-refused-already-liquidatable"] = await get("/cover/quote?address=0x976EA74026E726554dB657fA54763abd0C3a0aa9");
  resetLoanStub();

  // REFUSED: unsupported collateral (wstETH). On the real path, `readLoan` detects that
  // no supported aToken has a balance, names the held asset via `nameUnsupportedCollateral`,
  // and refuses. The stub returns the refusal directly with the real message template,
  // filled in with wstETH -- the most common case that Aave borrowers on Base hit.
  loanState.next = {
    ok: false,
    refusal: {
      code: "UNSUPPORTED_COLLATERAL",
      message:
        "This Loan is collateralised with wstETH, which a Cover cannot hedge. Only WETH and cbBTC are " +
        "supported. wstETH, cbETH and weETH are deliberately excluded: they drift against ETH over time, " +
        "so an ETH put under-hedges them by a margin that grows.",
    },
  };
  generated["cover-refused-unsupported-collateral"] = await get("/cover/quote?address=0x14dC79964da2C08b23698B3D3cc7Ca32193d9955");
  resetLoanStub();

  // REFUSED: nothing supplied to Aave at all. On the real path, `totalCollateralUsd <= 0`
  // and no aToken balance is held, so `readLoan` refuses with NO_COLLATERAL. The address
  // in the message matches the one used in the get() call below -- that is what the real
  // route does: it embeds the address that was asked about.
  loanState.next = {
    ok: false,
    refusal: {
      code: "NO_COLLATERAL",
      message:
        "0x23618e81E3f5cdF7f54C3d65f7FBc0aBf5B21E8f has nothing supplied to Aave V3 on Base, " +
        "so there is no Loan to cover. Check you are on Base and not another network.",
    },
  };
  generated["cover-refused-no-collateral"] = await get("/cover/quote?address=0x23618e81E3f5cdF7f54C3d65f7FBc0aBf5B21E8f");
  resetLoanStub();

  // --- Risk Profile / Suggestion / Decisions --------------------------------
  //
  // Two different kinds of fixture here, and the difference matters:
  //
  // "risk-profile-unset" and "suggestion-unset" are GENUINE server code: with no
  // saved profile, GET /risk-profile answers `{ profile: null }` and GET /suggestion
  // builds its own all-null object (app.ts, "No saved profile" branch) without ever
  // calling the agents service. Nothing about the ROUTE is mocked for those two --
  // only the Supabase accessor beneath it, the same way the fixture book stands in
  // for the chain elsewhere in this file.
  //
  // "risk-profile-balanced", "suggestion-eth", "suggestion-no-signal" and
  // "decisions-accepted" are mocked-passthrough captures: the value returned is
  // whatever this file told the mock to return, not something the server derived.
  // What they're actually worth is capturing the ENVELOPE the route builds around
  // that value -- so a route rename or a response-shape change still breaks
  // generation loudly, even though the payload inside is fabricated here rather
  // than computed by real Supabase or Python code.
  mockedGetProfile.mockResolvedValueOnce(null);
  generated["risk-profile-unset"] = await getAsOwner("/risk-profile");

  mockedGetProfile.mockResolvedValueOnce(null);
  generated["suggestion-unset"] = await getAsOwner("/suggestion");

  mockedSetProfile.mockResolvedValueOnce({
    ownerId: OWNER,
    profile: "balanced",
    createdAt: "2026-09-01T00:00:00Z",
    updatedAt: "2026-09-01T00:00:00Z",
  });
  generated["risk-profile-balanced"] = await putAsOwner("/risk-profile", { profile: "balanced" });

  mockedGetProfile.mockResolvedValueOnce("balanced");
  mockedFetchSuggestion.mockResolvedValueOnce({
    profile: "balanced",
    strategyId: "rsi-oversold-eth",
    strategyName: "RSI oversold bounce",
    firedAt: "2026-01-14T00:00:00Z",
    coverSummary: "Buys a modest cover and holds it only briefly.",
    marketBand: "weak",
    intent,
    asOf: "2026-01-15T00:00:00Z",
  });
  generated["suggestion-eth"] = await getAsOwner("/suggestion");

  // The same Suggestion asked over three days -- an expiry the book does not quote, so
  // the proposal it deals comes back on a different one. Pairs with "propose-horizon-3".
  mockedGetProfile.mockResolvedValueOnce("balanced");
  mockedFetchSuggestion.mockResolvedValueOnce({
    profile: "balanced",
    strategyId: "rsi-oversold-eth",
    strategyName: "RSI oversold bounce",
    firedAt: "2026-01-14T00:00:00Z",
    coverSummary: "Buys a modest cover and holds it only briefly.",
    marketBand: "weak",
    intent: { ...intent, horizonDays: 3 },
    asOf: "2026-01-15T00:00:00Z",
  });
  generated["suggestion-eth-3d"] = await getAsOwner("/suggestion");

  // A saved profile, but the Strategy Agent's RSI check did not fire -- the "nothing
  // to suggest" case, distinct from an unset profile (which never calls Python at
  // all, per the comment above).
  mockedGetProfile.mockResolvedValueOnce("balanced");
  mockedFetchSuggestion.mockResolvedValueOnce({
    profile: "balanced",
    strategyId: null,
    strategyName: null,
    firedAt: null,
    coverSummary: null,
    marketBand: null,
    intent: null,
    asOf: "2026-01-15T00:00:00Z",
  });
  generated["suggestion-no-signal"] = await getAsOwner("/suggestion");

  mockedRecordDecision.mockResolvedValueOnce({
    id: "decision-1",
    ownerId: OWNER,
    strategyId: "rsi-oversold-eth",
    strategyName: "RSI oversold bounce",
    firedAt: "2026-01-14T00:00:00Z",
    then: intent as any,
    decision: "ACCEPTED",
    decidedAt: "2026-01-15T00:00:05Z",
  });
  generated["decisions-accepted"] = await postAsOwner("/decisions", {
    strategyId: "rsi-oversold-eth",
    strategyName: "RSI oversold bounce",
    firedAt: "2026-01-14T00:00:00Z",
    intent,
    decision: "ACCEPTED",
  });

  // --- History ---------------------------------------------------------------
  //
  // A mocked-passthrough capture, same reasoning as "decisions-accepted" above:
  // `../supabase/fills.js` is mocked at its module boundary (same convention as
  // `history.test.ts`), so what this captures is the ENVELOPE `/history` builds
  // around a Fill -- the Figure formatting, the field names -- not something the
  // route derived itself. Two rows: a Deck buy and an RFQ buy, so the browser
  // suite has both `kind`s to render.
  mockedListFills.mockResolvedValueOnce([
    {
      id: "fill-2",
      ownerId: OWNER,
      walletAddress: TRADER_ADDRESS,
      kind: "RFQ",
      underlying: "SOL",
      isCall: true,
      strike: 105,
      contracts: 1,
      premiumUsdc: 1.25,
      expiryIso: "2026-01-29T08:00:00.000Z",
      optionAddress: null,
      txHash: "0xfeedfacefeedfacefeedfacefeedfacefeedfacefeedfacefeedfacefeedface",
      filledAt: "2026-01-15T10:30:00.000Z",
    },
    {
      id: "fill-1",
      ownerId: OWNER,
      walletAddress: TRADER_ADDRESS,
      kind: "DECK",
      underlying: "ETH",
      isCall: false,
      strike: 2400,
      contracts: 0.869434,
      premiumUsdc: 2,
      expiryIso: "2026-01-16T08:00:00.000Z",
      optionAddress: "0x0000000000000000000000000000000000000aa",
      txHash: "0xdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
      filledAt: "2026-01-14T09:00:00.000Z",
    },
  ]);
  generated["history"] = await getAsOwner("/history");
});

/**
 * The fixture as content, not as bytes.
 *
 * Line endings are not part of the contract. Git hands these files back with CRLF on a
 * Windows checkout, so a byte comparison calls every fixture stale after a branch
 * switch -- a failure about the filesystem wearing the costume of a failure about the API.
 */
const onDisk = (path: string) => readFileSync(path, "utf8").split("\r\n").join("\n");

describe("the fixtures the browser suite runs against", () => {
  it.each(NAMES)("%s matches what the API produces", (name) => {
    expect(generated[name], `${name} was never generated`).toBeDefined();

    const path = join(DIR, `${name}.json`);
    const body = `${JSON.stringify(stabilise(generated[name]), null, 2)}\n`;

    if (WRITE) {
      mkdirSync(DIR, { recursive: true });
      writeFileSync(path, body);
      return;
    }

    expect(existsSync(path), `${name}.json is missing -- run \`npm run fixtures\``).toBe(true);
    expect(onDisk(path), `${name}.json is stale -- run \`npm run fixtures\``).toBe(body);
  });
});
