/**
 * The API responses the browser tests are driven against, generated by the real API.
 *
 * The frontend suite stubs the network, which raises the obvious question: stubbed with
 * what? Hand-written JSON would drift from the contract the moment a field moved, and
 * the browser tests would keep passing against a server that no longer exists.
 *
 * So the fixtures are produced by driving the actual Fastify app -- the same routes, the
 * same pricing path, the same formatting -- with the Thetanuts client stubbed at its
 * module boundary. This file then asserts the checked-in copies still match. A backend
 * change that alters a response shape fails HERE, with an instruction, rather than
 * silently leaving the browser suite testing a fiction.
 *
 *     npm run fixtures      # regenerate after a deliberate contract change
 */
import { describe, it, expect, beforeAll, afterAll, vi } from "vitest";

vi.mock("../thetanuts/client.js", async () => await import("./stub-client.js"));

import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";
import type { FastifyInstance } from "fastify";
import { buildApp } from "../app.js";
import { resetStub, state } from "./stub-client.js";
import { NOW, makeOrder } from "./fixtures.js";

vi.useFakeTimers({ toFake: ["Date"] });
vi.setSystemTime(NOW);
afterAll(() => vi.useRealTimers());

const DIR = fileURLToPath(new URL("../../../web/tests/fixtures/", import.meta.url));
const WRITE = process.env.WRITE_FIXTURES === "1";

/** The session every fixture is generated under, so its cardRefs resolve against each other. */
const SESSION = "fixtures";

/**
 * Every fixture, named up front.
 *
 * Static because `it.each` is evaluated at collection time, before anything has been
 * generated -- and because naming them here makes deleting one that the browser suite
 * depends on a failure rather than a route it mysteriously cannot stub.
 */
const NAMES = [
  "deck-down-1",
  "deck-down-2",
  "deck-down-3",
  "deck-up-1",
  "deck-empty",
  "deck-compressed",
  "session",
  "positions-empty",
  "positions-after-practice",
  "propose-agent",
  "propose-by-card",
  "practice",
  "veto",
  "no-order",
  "refusal",
] as const;

/**
 * Replace the capabilities with stable stand-ins.
 *
 * A `cardRef` is an HMAC under a per-session random key and a `proposalId` is a
 * randomUUID -- both unguessable by design, both different on every run. Comparing them
 * byte for byte would make this file fail every time it was run, so they are numbered in
 * order of first appearance instead.
 *
 * What survives is what the browser suite actually depends on: the figures, the strings,
 * the ordering, and the fact that a ref appearing in a Deck is the same ref the proposal
 * for that Card comes back under.
 */
function stabilise(value: unknown): unknown {
  const seen = new Map<string, string>();
  const swap = (s: string) => {
    if (/^[0-9a-f]{32}$/.test(s)) return seen.get(s) ?? (seen.set(s, `card-${seen.size}`), seen.get(s)!);
    if (/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/.test(s)) return "proposal-id";
    return s;
  };
  const walk = (v: unknown): unknown => {
    if (typeof v === "string") return swap(v);
    if (Array.isArray(v)) return v.map(walk);
    if (v && typeof v === "object")
      return Object.fromEntries(Object.entries(v).map(([k, val]) => [swap(k), walk(val)]));
    return v;
  };
  return walk(value);
}

let app: FastifyInstance;
const generated: Record<string, unknown> = {};

const get = async (url: string, session = SESSION) =>
  (await app.inject({ method: "GET", url, headers: { "x-session-id": session } })).json();

// `payload` is typed rather than left as `unknown`, which sends TypeScript down a
// different `inject` overload and loses the response type entirely.
const post = async (url: string, payload: Record<string, unknown>, session = SESSION) =>
  await app.inject({ method: "POST", url, headers: { "x-session-id": session }, payload });

const DOWN_1 = "/deck?direction=DOWN&horizonDays=1&sizeUsdc=2";
const intent = { underlying: "ETH", direction: "DOWN", sizeUsdc: 2, horizonDays: 1 };

beforeAll(async () => {
  resetStub();
  app = await buildApp();

  // --- the ordinary surface -------------------------------------------------
  generated["deck-down-1"] = await get(DOWN_1);
  generated["deck-down-2"] = await get("/deck?direction=DOWN&horizonDays=2&sizeUsdc=2");
  generated["deck-down-3"] = await get("/deck?direction=DOWN&horizonDays=3&sizeUsdc=2");
  generated["deck-up-1"] = await get("/deck?direction=UP&horizonDays=1&sizeUsdc=2");
  generated["session"] = await get("/session");
  generated["positions-empty"] = await get("/positions");

  // The Trade Agent's own pick, and then every Card as an override -- so a browser test
  // can flick across the whole Deck and get the answer the server would really give.
  generated["propose-agent"] = (await post("/propose", intent)).json();

  const deck = generated["deck-down-1"] as { cards: Array<{ cardRef: string }> };
  const byCard: Record<string, unknown> = {};
  for (const card of deck.cards) {
    byCard[card.cardRef] = (await post("/propose", { ...intent, cardRef: card.cardRef })).json();
  }
  generated["propose-by-card"] = byCard;

  // A Practice Run against a freshly minted proposal, plus the board it produces.
  const forPractice = (await post("/propose", intent)).json() as { proposalId: string };
  generated["practice"] = (await post("/practice", { proposalId: forPractice.proposalId })).json();
  generated["positions-after-practice"] = await get("/positions");

  // --- the halt states ------------------------------------------------------
  process.env.COPILOT_REVIEW_FIXTURE = "veto";
  generated["veto"] = (await post("/propose", intent, "veto-session")).json();
  delete process.env.COPILOT_REVIEW_FIXTURE;

  state.book = [];
  generated["deck-empty"] = await get(DOWN_1, "empty-session");
  generated["no-order"] = (await post("/propose", intent, "empty-session")).json();

  // --- a Deck whose chances have compressed, so the gradient stops carrying ---
  state.book = [
    makeOrder({ nonce: 30, optionType: 1, strike: 2440, perContract: 9.6, days: 1, iv: 0.45 }),
    makeOrder({ nonce: 30, optionType: 1, strike: 2445, perContract: 10.4, days: 1, iv: 0.45 }),
    makeOrder({ nonce: 30, optionType: 1, strike: 2450, perContract: 11.2, days: 1, iv: 0.45 }),
  ];
  generated["deck-compressed"] = await get(DOWN_1, "compressed-session");

  // --- the Trader's own ceiling refusing them -------------------------------
  resetStub();
  await post("/session/budget", { riskBudgetUsdc: 1 }, "broke-session");
  const refused = await post("/propose", intent, "broke-session");
  generated["refusal"] = { status: refused.statusCode, body: refused.json() };
});

/**
 * The fixture as content, not as bytes.
 *
 * Line endings are not part of the contract. Git hands these files back with CRLF on a
 * Windows checkout, so a byte comparison calls every fixture stale after a branch
 * switch -- a failure about the filesystem wearing the costume of a failure about the API.
 */
const onDisk = (path: string) => readFileSync(path, "utf8").split("\r\n").join("\n");

describe("the fixtures the browser suite runs against", () => {
  it.each(NAMES)("%s matches what the API produces", (name) => {
    expect(generated[name], `${name} was never generated`).toBeDefined();

    const path = join(DIR, `${name}.json`);
    const body = `${JSON.stringify(stabilise(generated[name]), null, 2)}\n`;

    if (WRITE) {
      mkdirSync(DIR, { recursive: true });
      writeFileSync(path, body);
      return;
    }

    expect(existsSync(path), `${name}.json is missing -- run \`npm run fixtures\``).toBe(true);
    expect(onDisk(path), `${name}.json is stale -- run \`npm run fixtures\``).toBe(body);
  });
});
